name: Weekly Lab Pipeline

on:
  schedule:
    - cron: '0 12 * * 1' # Every Monday at Noon UTC
  workflow_dispatch:      # Allows you to click "Run Now" button manually

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for Azure Login

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login (The Robot Badge)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Pipeline Script
        run: python 2_process_data.py
        env:
          # In the cloud, we swap local paths for Azure URLs
          AZURE_STORAGE_ACCOUNT: "mylabstorage"